/*
 * wspr_transmit.c
 *
 * Baby-step WSPR transmitter command.
 *
 * Current fixed message:
 *
 *   VK2JPG QF56 3
 *
 * Run as:
 *
 *   sudo ./wspr_transmit VK2JPG QF56 3
 *
 * This version does not yet encode arbitrary callsigns in C.
 * It uses the 162 symbols already generated by print_wspr_symbols.py.
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>

#include "si5351_wspr.h"

/*
 * WSPR symbols for:
 *   callsign = VK2JPG
 *   locator  = QF56
 *   power    = 3
 */
static const uint8_t symbols[162] = {
    3, 3, 2, 0, 0, 0, 2, 2, 1, 2, 2, 0, 3, 1, 1, 2, 2, 0,
    3, 2, 0, 3, 2, 3, 3, 1, 3, 2, 2, 2, 0, 0, 0, 2, 1, 2,
    2, 3, 2, 3, 2, 2, 2, 2, 0, 0, 1, 2, 3, 3, 0, 2, 3, 1,
    0, 1, 2, 0, 0, 3, 3, 2, 1, 2, 2, 0, 2, 3, 1, 0, 1, 0,
    1, 2, 1, 2, 1, 0, 2, 1, 2, 0, 1, 0, 1, 1, 0, 0, 2, 1,
    3, 2, 1, 2, 3, 0, 0, 0, 1, 0, 2, 0, 0, 0, 3, 0, 2, 3,
    2, 2, 1, 1, 1, 2, 3, 1, 0, 0, 3, 3, 2, 3, 0, 0, 2, 1,
    1, 3, 2, 0, 2, 2, 2, 3, 2, 3, 2, 2, 3, 1, 2, 0, 0, 0,
    0, 2, 2, 3, 3, 2, 3, 0, 3, 1, 2, 0, 0, 3, 1, 0, 0, 0,
};

static void usage(const char *prog)
{
    printf("Usage:\n");
    printf("  sudo %s VK2JPG QF56 3\n", prog);
}

int main(int argc, char **argv)
{
    /*
     * Assignment-style command line:
     *
     *   ./wspr_transmit CALLSIGN LOCATOR POWER
     *
     * For this baby step, only our fixed generated message is supported.
     */
    if (argc != 4) {
        usage(argv[0]);
        return 1;
    }

    if (strcmp(argv[1], "VK2JPG") != 0 ||
        strcmp(argv[2], "QF56") != 0 ||
        strcmp(argv[3], "3") != 0) {
        printf("This baby-step build only supports:\n");
        printf("  VK2JPG QF56 3\n");
        return 1;
    }

    /*
     * RF frequency plan.
     *
     * Tone 0 starts at 7040100 Hz.
     * WSPR tone spacing is 12000 / 8192 = 1.46484375 Hz.
     */
    const double base_hz = 7040100.0;
    const double tone_spacing_hz = 12000.0 / 8192.0;
    const useconds_t symbol_us = 683000;

    printf("WSPR transmit started\n");
    printf("Message: %s %s %s\n", argv[1], argv[2], argv[3]);
    printf("Base CLK2: %.4f Hz\n", base_hz);
    printf("Tone spacing: %.8f Hz\n", tone_spacing_hz);
    printf("Symbol time: %u us\n", symbol_us);
    printf("Symbols: %u\n",
           (unsigned)(sizeof(symbols) / sizeof(symbols[0])));

    /*
     * Configure Si5351 once.
     *
     * Current simple driver returns void and exits internally on I2C failure.
     */
    si5351_init_wspr();

    /*
     * Step through the 162 WSPR symbols.
     */
    for (unsigned i = 0; i < sizeof(symbols) / sizeof(symbols[0]); i++) {
        uint8_t tone = symbols[i];
        double freq_hz = base_hz + tone * tone_spacing_hz;

        printf("symbol %u: tone %u, CLK2 %.4f Hz\n",
               i, tone, freq_hz);

        si5351_set_clk2_freq_hz(freq_hz);

        usleep(symbol_us);
    }

    si5351_close();

    printf("Done\n");
    return 0;
}